#!/usr/bin/env bash

active_workspace_monitor=$(hyprctl -j activeworkspace | jq -r '(.monitor)')
screenshot_filename="$HOME/Pictures/Screenshots/$(date +"%d-%m-%Y-%H%S")-$(active_workspace_monitor).png"

grim -o $active_workspace_monitor $screenshot_filename

if [ -e $screenshot_filename ]; then
  notify-send -u normal -t 2000 -i $screenshot_filename "Grim" "Screenshot Saved \n$screenshot_filename"
fi
